# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de7f46a70edfcf0f8bba28c71df48e7cc0579515371ced341668a6d4df5ef8489faa00a6075ad3fccd814576c2e4e1fb28c8ecfa902d98bb7f45426fd98c334a

test:
  secret_key_base: 54440b6cf980202b83c522db92f7ec2ab6a42b777ae17eada389906f5f658ab43602cf9fc2662b313436a20309f1d9c3ff166ba51a38dbcf9d84988e854ac79d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
